# ==========================================
# Site Settings (Edit these for your site)
# ==========================================
title: "John Doe"
tagline: "Your Catchy Tagline"
description: >-
  A brief description of your portfolio and blog. 
  This shows up in search engine results and social media previews.
url: "https://your-username.github.io"
email: "your-email@example.com"
og_image: "https://placehold.co/300x300?text=Profile+Photo" # Profile photo

# ==========================================
# Social Links (Leave empty to hide)
# ==========================================
social:
  github: "https://github.com/your-github-username"
  linkedin: "https://linkedin.com/in/your-linkedin-username"
  twitter: "https://twitter.com/your-twitter-username"
  instagram: "https://instagram.com/your-instagram-username"
  youtube: "https://youtube.com/channel/your-youtube-channel-id"

# ==========================================
# Giscus Comments Settings
# ==========================================
giscus: # Visit https://giscus.app/ to set up your Giscus comments and get the necessary IDs
  enabled: true # Toggle this to true to enable Giscus comments
  repo: "lakshyaelite/amazing-portfolio"
  repo_id: "R_kgDOR5tMrw"
  category: "Giscus"
  category_id: "DIC_kwDOR5tMr84C6FLz"
  mapping: "pathname"
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "top"
  theme: "preferred_color_scheme"
  lang: "en"

# ==========================================
# ! DO NOT EDIT BELOW THIS LINE UNLESS YOU KNOW WHAT YOU'RE DOING
# ==========================================
markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  syntax_highlighter_opts:
    disable_highlighting: true